const topics = [["01", "Why was this project created?", "/#/faq/why"], ["02", "How do I run it locally?", "/#/faq/local"], ["03", "How do I run it locally with Docker?", "/#/faq/docker"]] as const;

export function FaqPage() {
  return <main id="main" class="faq-page">
    <header class="faq-introduction"><p class="eyebrow">Q&amp;A / setup notes</p><h1>Understand the project.<br />Run it your way.</h1><p>This page covers why AI Demo exists and the shortest paths to running it locally—with or without Docker.</p></header>
    <div class="faq-layout">
      <aside class="faq-index" aria-label="Questions on this page"><p>On this page</p><ol>{topics.map(([number, question, href]) => <li key={href}><a href={href}><span>{number}</span>{question}</a></li>)}</ol></aside>
      <div class="faq-answers">
        <article id="why" class="faq-answer"><span class="faq-number" aria-hidden="true">01</span><div><p class="eyebrow">Project purpose</p><h2>Why was this project created?</h2><p>AI Demo is an educational Java 21 reference application. It makes provider-independent LLM integration, streaming, agents and tools, retrieval-augmented generation (RAG), and local or cloud execution understandable without hiding the core request flow behind an AI framework.</p></div></article>
        <article id="local" class="faq-answer"><span class="faq-number" aria-hidden="true">02</span><div><p class="eyebrow">Local setup</p><h2>How do I run it locally?</h2><p>This route runs the Java HTTP backend and the Vite frontend as two separate processes.</p><ol class="setup-steps">
          <li><h3>Install the prerequisites</h3><p>Install <a href="https://git-scm.com/downloads">Git</a>, a <a href="https://adoptium.net/temurin/releases/?version=21">Java 21 JDK</a>, <a href="https://maven.apache.org/download.cgi">Maven 3.9+</a>, <a href="https://nodejs.org/en/download">Node.js 20+</a>, and an IDE such as <a href="https://www.jetbrains.com/idea/download/">IntelliJ IDEA</a>. Check the command-line tools in PowerShell:</p><pre><code>{`git --version\njava --version\nmvn --version\nnode --version`}</code></pre></li>
          <li><h3>Download the project</h3><p>Clone the repository and enter its folder:</p><pre><code>{`git clone https://github.com/MartinBelas/ai-demo.git\ncd ai-demo`}</code></pre></li>
          <li><h3>Choose an LLM provider</h3><p>Open <code>src/main/resources/application.properties</code> and set <code>app.interface=http</code>. For the simplest fully local option, <a href="https://ollama.com/download">install Ollama</a>, keep <code>llm.provider=ollama</code> and <code>ollama.enabled=true</code>, then run:</p><pre><code>{`ollama pull qwen3:4b\nollama serve`}</code></pre><p>Alternatively, set <code>llm.provider=openai</code>, <code>groq</code>, or <code>gemini</code> and set the corresponding environment variable named in the configuration: <code>OPENAI_API_KEY</code>, <code>GROQ_API_KEY</code>, or <code>GEMINI_API_KEY</code>. Keep keys outside source files.</p></li>
          <li><h3>Build and verify the Java project</h3><pre><code>mvn verify</code></pre></li>
          <li><h3>Start the HTTP backend</h3><p>Import the folder as a Maven project in your IDE and run the Java main class <code>ai.demo.App</code>. This starts the HTTP backend—not the browser interface—on port 8080. Check it at <a href="http://localhost:8080/api/health">http://localhost:8080/api/health</a>.</p></li>
          <li><h3>Start the frontend</h3><p>Open a second PowerShell window in the repository root. This script installs frontend dependencies on its first run and starts Vite:</p><pre><code>./scripts/start-frontend.ps1</code></pre><p>Open <a href="http://localhost:5173">http://localhost:5173</a>. Vite forwards API requests to the backend on port 8080.</p></li>
        </ol><aside class="setup-summary"><p class="eyebrow">You should now have</p><dl><div><dt>Backend</dt><dd><a href="http://localhost:8080">localhost:8080</a></dd></div><div><dt>Frontend</dt><dd><a href="http://localhost:5173">localhost:5173</a></dd></div></dl></aside></div></article>
        <article id="docker" class="faq-answer"><span class="faq-number" aria-hidden="true">03</span><div><p class="eyebrow">Container setup</p><h2>How do I run it locally with Docker?</h2><p>Docker is the simplest complete setup: Java, Maven, Node.js, and a separate Ollama installation are not required on your computer.</p><ol class="setup-steps">
          <li><h3>Install Git and Docker</h3><p>Install <a href="https://git-scm.com/downloads">Git</a> to download the repository and <a href="https://www.docker.com/products/docker-desktop/">Docker Desktop</a> (or Docker Engine with Compose). Start Docker and wait until it reports that it is running, then verify:</p><pre><code>{`docker --version\ndocker compose version`}</code></pre></li>
          <li><h3>Download the project</h3><pre><code>{`git clone https://github.com/MartinBelas/ai-demo.git\ncd ai-demo`}</code></pre></li>
          <li><h3>Know what the first run downloads</h3><p>Compose downloads the application image <code>ghcr.io/martinbelas/ai-demo:latest</code> from GitHub Container Registry and <code>ollama/ollama:latest</code> from Docker Hub. Ollama then downloads the default <code>qwen3:4b</code> model into a persistent Docker volume. The first run can therefore be large and take some time.</p></li>
          <li><h3>Pull the images and start</h3><p>The first command downloads both referenced images before startup:</p><pre><code>{`docker compose --profile ollama pull\ndocker compose --profile ollama up -d`}</code></pre></li>
          <li><h3>Follow the model download</h3><pre><code>docker compose logs -f ollama-model</code></pre><p>Wait for the model pull to complete. Press <kbd>Ctrl+C</kbd> to leave the log view; this does not stop the containers.</p></li>
          <li><h3>Open the application</h3><p>Visit <a href="http://localhost:8080">http://localhost:8080</a>. You can also check the backend at <a href="http://localhost:8080/api/health">http://localhost:8080/api/health</a>.</p></li>
          <li><h3>Stop safely</h3><pre><code>docker compose --profile ollama down</code></pre><p>The downloaded model remains saved in its Docker volume for the next start.</p></li>
        </ol><aside class="advanced-note"><p class="eyebrow">Advanced / build local source</p><p>To build the application image from your current checkout instead of pulling the published application image, run:</p><pre><code>docker compose --profile ollama up -d --build</code></pre></aside></div></article>
      </div>
    </div>
  </main>;
}
